In [1]:
import pandas as pd
import os
from pathlib import Path

In [2]:
AI_LABEL_NAME = "label0"
NOT_AI_LABEL = 0
IS_AI_LABEL = 1

BULLSHIT_LABEL_NAME = "label1"
NOT_BULLSHIT_LABEL = 0
IS_BULLSHIT_LABEL = 1

In [3]:
BASE_DIR = "../"
if not os.path.isdir("data"):
    os.makedirs("data")

In [4]:
def process_data_files(input_dir, process_text, ai_label, bullshit_label, output_file):
    contents = []
    for f in Path(input_dir).iterdir():
        try:
            if f.is_file():
                text = process_text(f.read_text())
                contents.append(text)
        except UnicodeDecodeError as e:
            print(str(e.object)[:100]) # ignoring files with unicode errors.
    data = pd.DataFrame({
        "text": contents,
        AI_LABEL_NAME: ai_label,
        BULLSHIT_LABEL_NAME: bullshit_label
    })
    data.to_csv(output_file, index=False)
    return data

### Fake News

Non-AI Bullshit

In [5]:
def process_fake_news(text):
    text = text[1:-1] # remove start / end quotes
    text = text.replace('""', '"') # remove double quotes
    return text

data = process_data_files(
    input_dir=f'{BASE_DIR}human_bullshit/fake_news_files',
    process_text=process_fake_news,
    ai_label=NOT_AI_LABEL,
    bullshit_label=IS_BULLSHIT_LABEL,
    output_file="data/fake_news.csv"
)
data.head()

                                                text  label0  label1
0  Don’t CLICK that, stupid! Is this email from M...       0       1
1  Behind the headlines - conspiracies, cover-ups...       0       1
2  Email \nWith millions of eyes watching CNN for...       0       1
3  Maggie Hassan, left and Kelly Ayotte Hassan de...       0       1
4  George Takei Invited To Thanksgiving At The Ba...       0       1

### Mission

Non-AI Bullshit

In [6]:
def process_mission(text):
    return text[1:-1] # remove quotes

process_data_files(
    input_dir=f'{BASE_DIR}human_bullshit/mission_files',
    process_text=process_mission,
    ai_label=NOT_AI_LABEL,
    bullshit_label=IS_BULLSHIT_LABEL,
    output_file="data/mission.csv"
).head()

                                                text  label0  label1
0  Bringing health through food to as many people...       0       1
1  To provide an excellent environment for studen...       0       1
2  Teaching as a dialogue – the focus is on the s...       0       1
3  StartPro is a new kind of sports program to em...       0       1
4  Founded in 1854, Lincoln University, the natio...       0       1

### Political Manifestos

Non-AI Bullshit

In [7]:
def process_political_manifestos(text):
    return text[6:-1] # remove "text" header and quotes

process_data_files(
    input_dir=f'{BASE_DIR}human_bullshit/political_manifestos',
    process_text=process_political_manifestos,
    ai_label=NOT_AI_LABEL,
    bullshit_label=IS_BULLSHIT_LABEL,
    output_file="data/political_manifestos.csv"
).head()

                                                text  label0  label1
0  Fulfilling Britain’s great potential This gene...       0       1
1  ONE NATION, ONE PEOPLE. America is One Nation,...       0       1
2  PREAMBLE This year our Republican Party has gr...       0       1
3  OUR VISION FOR BRITAIN  FOREWORD by the Rt Hon...       0       1
4  The Best Future for Britain  FOREWORD  At the ...       0       1

### Spam Messages

Non-AI Bullshit

In [8]:
#TODO: handle encoding errors
contents_df = pd.read_csv(f'{BASE_DIR}human_bullshit/spam_msgs/spam.csv', encoding_errors='ignore')
contents_df = contents_df[contents_df['v1'] == "spam"]
data = pd.DataFrame({
    "text": contents_df['v2'], #TODO: process text
    AI_LABEL_NAME: NOT_AI_LABEL,
    BULLSHIT_LABEL_NAME: IS_BULLSHIT_LABEL,
}).reset_index(drop=True)
data.to_csv(f"data/spam_messages.csv", index=False)
data.head()

                                                text  label0  label1
0  Free entry in 2 a wkly comp to win FA Cup fina...       0       1
1  FreeMsg Hey there darling it's been 3 week's n...       0       1
2  WINNER!! As a valued network customer you have...       0       1
3  Had your mobile 11 months or more? U R entitle...       0       1
4  SIX chances to win CASH! From 100 to 20,000 po...       0       1

### Speech

Non-AI Bullshit

In [9]:
def process_speech(text):
    return text[1:-1] # remove "text" header and quotes

data = process_data_files(
    input_dir=f'{BASE_DIR}human_bullshit/speech_files',
    process_text=process_speech,
    ai_label=NOT_AI_LABEL,
    bullshit_label=IS_BULLSHIT_LABEL,
    output_file="data/speech.csv"
)
data.head()

                                                text  label0  label1
0  As you may have heard I took a few days off th...       0       1
1  Having flown back overnight from Washington, f...       0       1
2  Well, for me it’s been a year of jubilees. I’v...       0       1
3  Working for Election Victory This has been the...       0       1
4  One of the traditional sports of party confere...       0       1

### Vision Mission

Non-AI Bullshit

In [10]:
def process_vision_mission(text):
    return text[1:-1] # remove quotes

data = process_data_files(
    input_dir=f'{BASE_DIR}human_bullshit/vision_mission_files',
    process_text=process_vision_mission,
    ai_label=NOT_AI_LABEL,
    bullshit_label=IS_BULLSHIT_LABEL,
    output_file="data/vision_mission.csv"
)
data.head()

                                                text  label0  label1
0  To offer each and every person around the worl...       0       1
1  is to use our passion for technology, content ...       0       1
2  To be a leading, competitive, Nutrition, Healt...       0       1
3  Lifetime partner in automobiles and beyond.\n\...       0       1
4  Our vision is to lead the change towards circu...       0       1

### Arxiv

Non-AI Notshit

1. Arxiv summaries and abstracts are not mapped one-to-one in the data. Given our task we would not necessarily need to group them by title but treat them as independent data instead.

In [11]:
abstracts = pd.read_csv(f"{BASE_DIR}human_notshit/arxiv/arxiv_data_210930-054931.csv").abstracts.head(1000)
#TODO: process text
data = pd.DataFrame({
    "text": abstracts,
    AI_LABEL_NAME: NOT_AI_LABEL,
    BULLSHIT_LABEL_NAME: NOT_BULLSHIT_LABEL,
}).reset_index(drop=True)
data.to_csv(f"data/arxiv_abstracts.csv", index=False)
data.head()

                                                text  label0  label1
0  Graph neural networks (GNNs) have been widely ...       0       0
1  Deep networks and decision forests (such as ra...       0       0
2  Graph convolutional networks (GCNs) are powerf...       0       0
3  With the increasing popularity of Graph Neural...       0       0
4  Machine learning solutions for pattern classif...       0       0

In [12]:
summaries = pd.read_csv(f"{BASE_DIR}human_notshit/arxiv/arxiv_data.csv").summaries.head(1000)
#TODO: process text
data = pd.DataFrame({
    "text": summaries,
    AI_LABEL_NAME: NOT_AI_LABEL,
    BULLSHIT_LABEL_NAME: NOT_BULLSHIT_LABEL,
}).reset_index(drop=True)
data.to_csv(f"data/arxiv_summaries.csv", index=False)
data.head()

                                                text  label0  label1
0  Stereo matching is one of the widely used tech...       0       0
1  The recent advancements in artificial intellig...       0       0
2  In this paper, we proposed a novel mutual cons...       0       0
3  Consistency training has proven to be an advan...       0       0
4  To ensure safety in automated driving, the cor...       0       0

### BNC

Non-AI Notshit

In [13]:
def process_bnc(text):
    text = text[:text.rfind(' ')+1:]
    text = text[text.index('\n'):].strip()
    return text

data = process_data_files(
    input_dir=f'{BASE_DIR}human_notshit/non-BS-BNC',
    process_text=process_bnc,
    ai_label=NOT_AI_LABEL,
    bullshit_label=NOT_BULLSHIT_LABEL,
    output_file="data/bnc.csv"
)
data.head()

                                                text  label0  label1
0  I the defendant Doctor David   against a decis...       0       0
1  The item or the issue for discussion this afte...       0       0
2  this moist toilet tissue.\nOh very nice.\nYou ...       0       0
3  Has anybody come across those terms assertive ...       0       0
4  The twenty-third of the fourth \nWhat.\nwho is...       0       0

### Wikipedia

Non-AI Notshit

In [14]:
def process_wiki(text):
    return text

data = process_data_files(
    input_dir=f'{BASE_DIR}human_notshit/wikipedia/processed',
    process_text=process_wiki,
    ai_label=NOT_AI_LABEL,
    bullshit_label=NOT_BULLSHIT_LABEL,
    output_file="data/wiki.csv"
)
data.head()

                                                text  label0  label1
0  As of the census of 2010, there were 52 people...       0       0
1  "Wouldn't It Be Loverly" is a popular song by ...       0       0
2  The Samsung Galaxy S20 is a series of Android-...       0       0
3  Floreat contains a public primary school, a lo...       0       0
4  There are 36 states and union territories of I...       0       0

### Nature Articles

Non-AI Notshit

In [15]:
def process_nature(text):
    return text

data = process_data_files(
    input_dir=f'{BASE_DIR}human_notshit/nature_articles/processed',
    process_text=process_nature,
    ai_label=NOT_AI_LABEL,
    bullshit_label=NOT_BULLSHIT_LABEL,
    output_file="data/nature.csv"
)
data.head()

                                                text  label0  label1
0  A hallmark of Laughlin-type FQH states is the ...       0       0
1  Tundra ecosystems, covering a wide range of en...       0       0
2  Initial lymphatics, also called lymphatic capi...       0       0
3  Digestion of food comprising organic tissues s...       0       0
4  The distribution of variation will affect stud...       0       0

### Onion Articles

Non-AI Bullshit

In [16]:
def process_onion(text):
    return text

data = process_data_files(
    input_dir=f'{BASE_DIR}human_bullshit/onion_news/processed',
    process_text=process_onion,
    ai_label=NOT_AI_LABEL,
    bullshit_label=NOT_BULLSHIT_LABEL,
    output_file="data/onion.csv"
)
data.head()

                                                text  label0  label1
0  A new U.S. Department Of Labor study revealed ...       0       0
1  Straining to react to the surprising engagemen...       0       0
2  Startled by the sudden appearance of the shado...       0       0
3  In a nationwide study regarding Americans’ pre...       0       0
4  Standing at attention in honor of their fallen...       0       0

### Gemini Data

AI Data

In [17]:
import io
import zipfile

def texts_from_zip(zip_path):
    texts = []
    with zipfile.ZipFile(zip_path) as zf:
        entries = [name for name in zf.namelist() if not name.endswith("/")]
        total = len(entries)
        for idx, name in enumerate(entries, start=1):
            with zf.open(name) as fh:
                data = fh.read()

            if name.lower().endswith(".txt"):
                text = data.decode().strip()
                texts.append(text)

            if name.lower().endswith(".csv"):
                try:
                    df = pd.read_csv(io.BytesIO(data), on_bad_lines="skip")
                except:
                    continue

                if "text" in df.columns > 0:
                    value = str(df["text"].iloc[0]).strip()
                elif len(df.columns) == 1:
                    value = str(df.columns[0]).strip()
                else:
                    value = ""

                if value:
                    texts.append(value)

    return texts

bs_zip = f"{BASE_DIR}ai_detector_data/gemini_results_bs.zip"
nbs_zip = f"{BASE_DIR}ai_detector_data/gemini_results_nbs.zip"

bs_texts = texts_from_zip(bs_zip)
nbs_texts = texts_from_zip(nbs_zip)

ai_df = pd.DataFrame({
    "text": bs_texts + nbs_texts,
    AI_LABEL_NAME: IS_AI_LABEL,
    BULLSHIT_LABEL_NAME: [IS_BULLSHIT_LABEL] * len(bs_texts) + [NOT_BULLSHIT_LABEL] * len(nbs_texts),
}).reset_index(drop=True)

ai_df.to_csv("data/ai_gemini.csv", index=False)
ai_df.info()
ai_df.head()

<class 'pandas.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    418 non-null    str
 1   label0  418 non-null    int64
 2   label1  418 non-null    int64
dtypes: int64(2), str(1)
memory usage: 2.2 MB

                                                text  label0  label1
0  We envision a world where every baby is read t...       1       1
1  To be the Premier Beer Company Uniting People ...       1       1
2  We are dedicated to fostering a sustainable fu...       1       1
3  to foster the sustainable development of both ...       1       1
4  to focus on financing and investment that fuel...       1       1

### GPT Data

AI Data

In [19]:
import zipfile

gpt_zip = f"{BASE_DIR}ai_detector_data/gpt_articles.zip"
texts = []

def process(text):
    lines = text.splitlines()
    content = []
    for line in lines:
        if line.startswith("###") or line.startswith("**"):
            continue
        content.append(line)
    return "\n".join(content).strip()

with zipfile.ZipFile(gpt_zip) as zf:
    entries = [name for name in zf.namelist() if name.lower().endswith(".txt")]
    total = len(entries)
    for idx, name in enumerate(entries, start=1):
        with zf.open(name) as fh:
            text = fh.read().decode()
            texts.append(process(text))

ai_df = pd.DataFrame({
    "text": texts,
    AI_LABEL_NAME: IS_AI_LABEL,
    BULLSHIT_LABEL_NAME: NOT_BULLSHIT_LABEL,
}).reset_index(drop=True)

ai_df.to_csv("data/ai_gpt.csv", index=False)
ai_df.info()
ai_df.head()

<class 'pandas.DataFrame'>
RangeIndex: 1242 entries, 0 to 1241
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    1242 non-null   str
 1   label0  1242 non-null   int64
 2   label1  1242 non-null   int64
dtypes: int64(2), str(1)
memory usage: 9.1 MB

                                                text  label0  label1
0  In our investigation into the microbial mechan...       1       0
1  Recent advancements in the realm of energy sto...       1       0
2  In this study, we present a comprehensive asse...       1       0
3  In this study, we present novel insights into ...       1       0
4  In this study, we present novel findings regar...       1       0